
service: notes-api-tutorial
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:PutItem
  #     Resource: !GetAtt notesTable.Arn #hvata dole notesTable i njegov arn

plugins:
  - serverless-iam-roles-per-function

functions:
  createNote:
    handler: handler.createNote
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn 
    events:
      - http:
          method: post
          path: notes

  updateNote:
    handler: handler.updateNote
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn 
    events:
      - http:
          method: put
          path: notes/{id}

  deleteNote:
    handler: handler.deleteNote
    events:
      - http:
          method: delete
          path: notes/{id}
  
  readNote:
    handler: handler.getAllNotes
    events:
      - http:
          method: get
          path: notes
    

resources:
  Resources:
    notesTable:   #imee 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S #STRINg
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH

